# Generated by Django 5.1.3 on 2024-11-21 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='service/')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='coach/')),
                ('specialization', models.CharField(max_length=100)),
                ('classes', models.ManyToManyField(related_name='coachs_classes', to='gym.classes')),
            ],
        ),
        migrations.AddField(
            model_name='classes',
            name='coach_name',
            field=models.ManyToManyField(related_name='classes_coachs', to='gym.coach'),
        ),
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('repetitions', models.PositiveIntegerField()),
                ('sessions', models.PositiveIntegerField()),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises_classes', to='gym.classes')),
                ('coach_name', models.ManyToManyField(related_name='exercises_coachs', to='gym.coach')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.PositiveIntegerField()),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('image', models.ImageField(upload_to='student/')),
                ('coach_name', models.ManyToManyField(related_name='student_coache', to='gym.coach')),
                ('exercises', models.ManyToManyField(related_name='student_exercise', to='gym.exercises')),
            ],
        ),
        migrations.AddField(
            model_name='coach',
            name='student_name',
            field=models.ManyToManyField(related_name='coach_student', to='gym.student'),
        ),
    ]
